name: gocover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.25'

    - name: Set up Tinygo
      uses: acifani/setup-tinygo@v3

    - name: Build WASM
      run: make wasm-go

    - name: Cover Host
      run: make cover

    - name: Update Host coverage badge
      uses: ncruces/go-coverage-report@v0.3.1
      with:
        coverage-file: _dist/coverage.out
        module-dir: host-wazero-lmdb
        output-dir: host-wazero-lmdb
      continue-on-error: true
