name: gocover

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Set up Tinygo
      uses: acifani/setup-tinygo@v2
      with:
        tinygo-version: 0.38.0

    - name: Build WASM
      run: cd test && tinygo build -buildmode=wasi-legacy -target=wasi -opt=2 -gc=conservative -scheduler=none -o ../host/test.wasm module.go

    - name: Cover
      run: cd host && go test . -coverprofile coverage.out

    - name: Update coverage badge
      uses: kevburnsjr/go-coverage-report@base-dir
      with:
        coverage-file: host/coverage.out
      continue-on-error: true
      base-dir: host
