name: test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Set up Tinygo
      uses: acifani/setup-tinygo@v3

    - name: Set up Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.16.0

    - name: Build WASM Go
      run: make wasm-go

    - name: Build WASM Zig
      run: make wasm-zig

    - name: Test
      run: make test
