name: test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: Set up Tinygo
      uses: acifani/setup-tinygo@v3

    - name: Set up Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.16.0

    - name: Build wasm go
      run: cd test && tinygo build -buildmode=wasi-legacy -target=wasi -opt=2 -gc=conservative -scheduler=none -o ../host/test.wasm module.go

    - name: Build wasm zig
      run: cd test-zig && zig build --release=small && cp zig-out/bin/test-zig.wasm ../host/test.zig.wasm

    - name: Test
      run: cd host && go test . -v -cover
